service: advent

provider:
  name: aws
  runtime: python3.7
  region: ap-northeast-1
  iamRoleStatements:
  - Effect: "Allow"
    Action:
    - "s3:PutObject"
    - "s3:GetObject"
    - "s3:ListBucket"
    - "sqs:CreateQueue"
    - "sqs:DeleteQueue"
    - "sqs:SendMessage"
    - "sqs:GetQueueUrl"
    Resource: "*"

functions:
  hello:
    handler: handler.hello
    events:
    - http:
        path: hello
        method: get
        cors: true

  sendmessage:
    handler: sendmessage.index

  receivemessage:
    handler: receivemessage.index
    events:
      - sqs:
          arn:
            Fn::Join:
            - ':'
            - - arn
              - aws
              - sqs
              - Ref: AWS::Region
              - Ref: AWS::AccountId
              - "hogehoge-queue"

  sthree-put:
    handler: sthreeput.index

  sthree-receive:
    handler: sthreereceive.index
    events:
    - s3:
        bucket: "sthreebucket-hogehoge"
        event: s3:ObjectCreated:*

resources:
  Resources:
    hogehogeQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: "hogehoge-queue"
